---
# tasks file for vitalied.postgresql

- name: apt-key add
  apt_key:
    url={{ postgresql_apt_key_url }}
    state=present
  tags: vitalied.postgresql

- name: apt-add-repository
  apt_repository:
    filename=postgresql
    repo={{ postgresql_add_apt_repo }}
    state=present
  tags: vitalied.postgresql

- name: apt-get install
  apt:
    name={{ item }}
    state=latest
  with_items: '{{ postgresql_packages }}'
  notify: restart postgresql
  tags: vitalied.postgresql

- name: check if new DB directory is empty
  stat: path={{ postgresql_data_dir }}/PG_VERSION
  register: postgresql_data_moved
  tags: vitalied.postgresql

- block:
  - name: stop postgresql
    service:
      name=postgresql
      state=stopped
    register: postgresql_stopped

  - name: create postgresql base directory
    file:
      path={{ postgresql_base_dir }}
      state=directory
      owner=postgres
      group=postgres

  - name: move DB data to new directory
    command: mv {{ postgresql_old_base_dir }}/{{ postgresql_version }} {{ postgresql_base_dir }}

  when: not postgresql_data_moved.stat.exists and postgresql_base_dir != postgresql_old_base_dir
  tags: vitalied.postgresql

- name: copy postgresql configuration
  template:
    src=etc/postgresql/postgresql.conf.j2
    dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    owner=postgres
    group=postgres
    mode=0644
  notify: restart postgresql
  tags: vitalied.postgresql

- name: copy postgresql security configuration
  template:
    src=etc/postgresql/pg_hba.conf.j2
    dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner=postgres
    group=postgres
    mode=0644
  notify: restart postgresql
  tags: vitalied.postgresql

- name: enable postgresql service
  service:
    name=postgresql
    enabled=yes
  notify: restart postgresql
  tags: vitalied.postgresql

- name: start postgresql
  service:
    name=postgresql
    state=started
  when: postgresql_stopped.changed
  tags: vitalied.postgresql
